# Generated by Django 5.0.4 on 2024-04-28 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_qrcode_qr_qrcode_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pay Bill', max_length=20, null=True)),
                ('business_number', models.CharField(max_length=200, null=True, unique=True)),
                ('account_number_or_name', models.CharField(max_length=200, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeForBuyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='qr_codes/')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeForPayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='qr_codes/')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
        migrations.RenameField(
            model_name='buygoods',
            old_name='code',
            new_name='till_number',
        ),
        migrations.AddField(
            model_name='qrcodeforbuygoods',
            name='pay_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.buygoods'),
        ),
        migrations.AddField(
            model_name='qrcodeforpaybill',
            name='pay_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.buygoods'),
        ),
    ]
