# Generated by Django 5.0.4 on 2024-04-28 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeforbuygoods',
            name='pay_type',
        ),
        migrations.AddField(
            model_name='qrcodeforbuygoods',
            name='till_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcodeforbuygoods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
