# Generated by Django 5.0.4 on 2024-04-28 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_qrcodeforbuygoods_pay_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeforpaybill',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='paybill',
            name='user',
        ),
        migrations.AddField(
            model_name='qrcodeforpaybill',
            name='account_number_or_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcodeforpaybill',
            name='business_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcodeforpaybill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BuyGoods',
        ),
        migrations.DeleteModel(
            name='PayBill',
        ),
    ]
